[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
MQTTLevel=1

[MQTT]
Address=127.0.0.1
Port=1883
Keepalive=60
Name=info
Auth=0
Username=mmdvm
Password=mmdvm

[Exclude]
# Used for MQTT access, DMR networks, and APRS-IS
Key=Password
# For DAPNET
Key=AuthKey

[Configs]
APRSGateway=../APRSGateway/APRSGateway.ini
DAPNETGateway=../DAPNETGateway/DAPNETGateway.ini
DGIdGateway=../YSFClients/DGIdGateway/DGIdGateway.ini
DMRGateway=../DMRGateway/DMRGateway.ini
DStarGateway=../DStarGateway/DStarGateway.ini
FMGateway=../FMGateway/FMGateway.ini
MMDVM-CrossMode=../MMDVM-CrossMode/MMDVM-CrossMode.ini
MMDVM-Host=../MMDVM-Host/MMDVM-Host.ini
MMDVM-IQ=../MMDVM-IQ/MMDVM-IQ.ini
NXDNGateway=../NXDNClients//NXDNGateway/NXDNGateway.ini
P25Gateway=../P25Clients/P25Gateway/P25Gateway.ini
YSFGateway=../YSFClients/YSFGateway/YSFGateway.ini

[Programs]
Refresh=60
Program=APRSGateway
Program=MMDVM-CrossMode
Program=DAPNETGateway
Program=DGIdGateway
Program=DMRGateway
Program=DStarGateway
Program=FMGateway
Program=MMDVM-IQ
Program=MMDVMHost
Program=NXDNGateway
Program=P25Gateway
Program=YSFGateway
