[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
MQTTLevel=1

[MQTT]
Address=127.0.0.1
Port=1883
Keepalive=60
Name=info
Auth=0
Username=mmdvm
Password=mmdvm

[Exclude]
# Used for MQTT access, DMR networks, and APRS-IS
Key=Password
# For DAPNET
Key=AuthKey

[Configs]
APRSGateway=../APRSGateway/APRSGateway.ini
CrossMode=../MMDVM-CrossMode/MMDVM-CrossMode.ini
DAPNETGateway=../DAPNETGateway/DAPNETGateway.ini
DGIdGateway=../YSFClients/DGIdGateway/DGIdGateway.ini
DMRGateway=../DMRGateway/DMRGateway.ini
DStarGateway=../DStarGateway/DStarGateway.ini
FMGateway=../FMGateway/FMGateway.ini
MMDVM-IQ=../MMDVM-IQ/MMDVM-IQ.ini
MMDVMHost=../MMDVMHost/MMDVMHost.ini
NXDNGateway=../NXDNClients//NXDNGateway/NXDNGateway.ini
P25Gateway=../P25Clients/P25Gateway/P25Gateway.ini
YSFGateway=../YSFClients/YSFGateway/YSFGateway.ini
